apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
      tier: backend
      track: stable
  replicas: 1
  strategy: Recreate
  template:
    metadata:
      labels:
        app: db
        tier: backend
        track: stable
    spec:
      containers:
        - name: db
          image: 'public.ecr.aws/ubuntu/postgres:12-20.04_beta'
          volumeMounts:
             - mountPath: /var/lib/postgresql/data
               name: db-volume
          env:
          - name: POSTGRES_PASSWORD
            value: DBPWPLACEHOLDER
          - name: POSTGRES_USER
            value: '433'
          - name: POSTGRES_DB
            value: 'userdb'
          ports:
          - containerPort: 5432
          volumes:
          - name: test-volume
            # This AWS EBS volume must already exist.
            awsElasticBlockStore:
              volumeID: "vol-07c8f57fd91cb3b7f"
              fsType: ext4