# Stage 1
FROM node:latest as build
WORKDIR /usr/src/app
COPY ./ /usr/src/app/
RUN echo ./.npmrc
RUN npm install
# TODO: austauschen wenn gefixt
# RUN export NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

# Stage 2
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/data-collector-login /usr/share/nginx/html
EXPOSE 80
