x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ELB}

services:
  backenddb:
    image: public.ecr.aws/docker/docker/library/postgres:latest
  #  image: postgres
    environment:
      POSTGRES_PASSWORD: '${DB_SECRET}'
      POSTGRES_USER: '{$DB_USER}'
      POSTGRES_DB: 'userdb'
    volumes:
      - data:/var/lib/postgresql/data
    networks:  
      - dbnet

  dbprepare:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:relayP$IMAGE_TAG
    #build: ./relay
    depends_on:
      - backenddb
    environment:
      SERVERHOST: 'localhost'
      SERVERPORT: '433'
      DBPASSWORD: '${DB_SECRET}'
      DBUSER: '${DB_USER}'
      DBNAME: 'userdb'
      DBPORT: '5432'
      DBHOST: 'backenddb'
    command: setup
    networks:
      - dbnet
    
  relay:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:relay$IMAGE_TAG
#    build: ./relay
    depends_on:
      - dbprepare
    environment:
      SERVERHOST: 'localhost'
      SERVERPORT: '433'
      DBPASSWORD: '${DB_SECRET}'
      DBUSER: '${DB_USER}'
      DBNAME: 'userdb'
      DBPORT: '5432'
      DBHOST: 'backenddb'
    command: serve
    networks:
      - dbnet
      - frontbacknet
    ports:
      - 433:433
  
  frontend: 
    image: $ECR_REGISTRY/$ECR_REPOSITORY:frontend$IMAGE_TAG
 #   build: ./frontend
    environment:
       RELAYHOST: 'relay'
    depends_on:
      - relay
    networks:
      - frontbacknet
    ports:
      - 80:80


volumes:
  data:

networks:
  frontbacknet:
  dbnet:
