apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "IMGPLACEHOLDER"
          env:
          - name: API_URL
            value: relay-service
          - name: API_PORT
            value: '2532'
          ports:
          - containerPort: 80
      nodeSelector:
        disktype: db