apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgress-ebs
  resources:
    requests:
      storage: 2Gi