@startuml register
title Webauthn register
participant Relay as relay
box Internal
participant "API-Server" as api
participant Host as host 
participant Enclave as enclave 
end box

' Register
== Registration == 
' Step 01
relay -> api : **[HTTPS]** /register/initialize
activate relay
activate api

api -> host : host_create_nonce()
activate host 

host -> enclave : enclave_create_nonce()
activate enclave 
enclave --> host : ret 
deactivate enclave

host --> api : ret 
deactivate host 

api --> relay : return challenge 
deactivate api 
deactivate relay

' Step 02
relay -> api : **[HTTPS]** /register/finalize
activate relay 
activate api 

api -> host : host_store_ecc_pk()
activate host

host -> enclave : enclave_store_ecc_pk()
activate enclave
enclave -> enclave : seal.seal_store()
activate enclave
enclave -> host : host_store_data()
host --> enclave : ret 
enclave --> enclave : ret 
deactivate enclave 
enclave --> host : ret 
deactivate enclave 
host --> api : ret 
deactivate host 
api --> relay : return \n<color green>**HTTP 200 OK**</color> \nor\n<color red>**HTTP ERROR**</color>
deactivate api 
deactivate relay
@enduml